src/Infra/Symfony/Persistance/Doctrine/Entity/Video.php
<?php

declare(strict_types=1);

namespace Infra\Symfony\Persistance\Doctrine\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Infra\Symfony\Persistance\Doctrine\Repository\VideoRepository;

#[ApiResource]
#[ORM\Entity(repositoryClass: VideoRepository::class)]
class Video implements \Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private $id;

    #[ORM\Column(type: Types::STRING, length: 255)]
    private string $name;

    #[ORM\Column(type: Types::STRING, length: 255)]
    private string $url;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTime $recordDate = null;

    #[ORM\Column(type: Types::STRING, length: 5, nullable: true)]
    private ?string $country = null;

    #[ORM\ManyToMany(targetEntity: Section::class, inversedBy: 'videos')]
    private $sections;

    #[ORM\OneToMany(targetEntity: PlaylistVideo::class, mappedBy: 'video', orphanRemoval: true)]
    private $playlistVideos;

    #[ORM\ManyToOne(targetEntity: Event::class, inversedBy: 'video', cascade: ['persist'])]
    private $event;

    #[ORM\Column(type: Types::TEXT, length: 4000, nullable: true)]
    private ?string $description = null;

    public function __construct()
    {
        $this->sections = new ArrayCollection();
        $this->playlistVideos = new ArrayCollection();
    }

    public function __toString(): string
    {
         return $this->getName() ?? '';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getRecordDate(): ?\DateTimeInterface
    {
        return $this->recordDate;
    }

    public function setRecordDate(?\DateTimeInterface $recordDate): self
    {
        $this->recordDate = $recordDate;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * @return Collection|Section[]
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): self
    {
        if (!$this->sections->contains($section)) {
            $this->sections[] = $section;
        }

        return $this;
    }

    public function removeSection(Section $section): self
    {
        if ($this->sections->contains($section)) {
            $this->sections->removeElement($section);
        }

        return $this;
    }

    /**
     * @return Collection|PlaylistVideo[]
     */
    public function getPlaylistVideos(): Collection
    {
        return $this->playlistVideos;
    }

    public function addPlaylistVideo(PlaylistVideo $playlistVideo): self
    {
        if (!$this->playlistVideos->contains($playlistVideo)) {
            $this->playlistVideos[] = $playlistVideo;
            $playlistVideo->setVideo($this);
        }

        return $this;
    }

    public function removePlaylistVideo(PlaylistVideo $playlistVideo): self
    {
        if ($this->playlistVideos->contains($playlistVideo)) {
            $this->playlistVideos->removeElement($playlistVideo);
            // set the owning side to null (unless already changed)
            if ($playlistVideo->getVideo() === $this) {
                $playlistVideo->setVideo(null);
            }
        }

        return $this;
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(Event $event): self
    {
        $this->event = $event;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getYoutubeId()
    {
        return $this->getYoutubeViedeoId($this->getUrl());
    }

    private function getYoutubeViedeoId($youtube_video_url) {
        /**
         * Pattern matches
         * http://youtu.be/ID
         * http://www.youtube.com/embed/ID
         * http://www.youtube.com/watch?v=ID
         * http://www.youtube.com/?v=ID
         * http://www.youtube.com/v/ID
         * http://www.youtube.com/e/ID
         * http://www.youtube.com/user/username#p/u/11/ID
         * http://www.youtube.com/leogopal#p/c/playlistID/0/ID
         * http://www.youtube.com/watch?feature=player_embedded&v=ID
         * http://www.youtube.com/?feature=player_embedded&v=ID
         */
        $pattern = '%(?:youtube(?:-nocookie)?\.com/(?:[^/]+/.+/|(?:v|e(?:mbed)?)/|.*[?&]v=)|youtu\.be/)([^"&?/ ]{11})%i';

        // Checks if it matches a pattern and returns the value
        if (preg_match($pattern, (string) $youtube_video_url, $match)) {
            return $match[1];
        }

        // if no match return false.
        return false;
    }
}

src/Infra/Symfony/Controller/VideoController.php
<?php

declare(strict_types=1);

namespace Infra\Symfony\Controller;

use Infra\Symfony\Persistance\Doctrine\Entity\Video;
use Infra\Symfony\Form\Type\SearchVideoType;
use Infra\Symfony\Persistance\Doctrine\Repository\EventRepository;
use Infra\Symfony\Persistance\Doctrine\Repository\VideoRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/video')]
class VideoController extends BaseController
{
    #[Route('/', name:'app_video_index')]
    public function indexAction(VideoRepository $videoRepository): Response
    {
        $countries = $videoRepository->getCountryList();
        $form = $this->createForm(SearchVideoType::class, null, [
            'countries' => $countries
        ]);
        $videos = $videoRepository->findLastVideos(500);

        return $this->render('video/index.html.twig', [
            'videos' => $videos,
            'searchVideoform' => $form->createView(),
            'breadcrumb' => $this->getBreadcurmb()
        ]);
    }

    #[Route('/search', name:'app_video_search')]
    public function searchAction(VideoRepository $videoRepository): Response
    {
        $form = $this->createForm(SearchVideoType::class);
        $videos = $videoRepository->filterAll($this->getSqlParameterBag());

        return $this->render('video/search.html.twig', [
            'videos' => $videos,
            'searchVideoform' => $form->createView(),
            'breadcrumb' => $this->getBreadcurmb()
        ]);
    }

    #[Route('/{id}', name:'app_video_show', requirements: ['id' => '\d+'])]
    public function showAction(Video $video): Response
    {
        return $this->render('video/show.html.twig', [
            'video' => $video,
            'breadcrumb' => $this->getBreadcurmb()
        ]);
    }

    private function getBreadcurmb(): array
    {
        $breadcrumb = [];
        $breadcrumb['items'][] = ['title'=> 'Home', 'url' => '/'];
        $breadcrumb['items'][] = ['title'=> 'Media', 'url' => $this->generateUrl('app_media_index')];
        $breadcrumb['items'][] = ['title'=> 'Video'];

        return $breadcrumb;
    }

    #[Route('/feed', name:'app_video_feed')]
    public function feedAction(EventRepository $eventRepository): JsonResponse
    {
        $data = [];
        $events = $eventRepository->findBy([], ['date' => 'DESC']);

        foreach ($events as $event) {
            if (!$event->getVideos()->isEmpty()) {
                $eventData = [
                    'id' => $event->getId(),
                    'title' => $event->getName(),
                    'description' => $event->getVenue() .' '. $event->getDate()?->format('C'),
                    'image' => "https://www.vilagfa.be/fr/wp-content/uploads/sites/2/2015/05/plancher1.jpg",
                ];
                foreach ($event->getVideos() as $video) {
                    $videoData = [
                        'id' => $video->getId(),
                        'title' => $video->getName(),
                        'youtube' => $video->getUrl(),
                        'director' => $video->getCountry(),
                        'year' => 2022,
                        'ratings' => null,
                        'duration' => 780,
                        'description' => $event->getVenue() .' '. $event->getDate()?->format('C'),
                        'url' => "https://android-tv-classics.firebaseapp.com/content/le_voyage_dans_la_lun/media_le_voyage_dans_la_lun.mp4",
                        'art' => "https://img.youtube.com/vi/" .$video->getYoutubeId(). "/sddefault.jpg",
                    ];
                    $eventData['items'][] = $videoData;
                }
                $data['feed'][] = $eventData;
            }

        }
        $data['backgrounds'][] = 'https://www.vilagfa.be/fr/wp-content/uploads/sites/2/2015/05/plancher1.jpg';
        $data['backgrounds'][] = 'https://www.vilagfa.be/fr/wp-content/uploads/sites/2/2015/05/plancher1.jpg';
        $data['backgrounds'][] = 'https://www.vilagfa.be/fr/wp-content/uploads/sites/2/2015/05/plancher1.jpg';

        return new JsonResponse($data);
    }
}

templates/video/_form_filter.html.twig
<div id="fitler_video" class="widget-title">
    <div class="collapse" id="collapseVideoFilter">
        <form class="card card-body" action="{{ path('app_video_search') }}">
            <div class="row">
                <div class="col-md-3">
                    <h4 class="title-border">Événement</h4>
                    {{ form_widget(searchVideoform.event) }}
                </div>

                <div class="col-md-3">
                    <h4 class="title-border">Pays</h4>
                    {{ form_widget(searchVideoform.country) }}
                </div>

                <div class="col-md-3">
                    <h4 class="title-border">Section</h4>
                    {{ form_widget(searchVideoform.sections) }}
                </div>

                <div class="col-md-3">
                    <h4 class="title-border">Tags</h4>

                    <select name="tags" class="form-control">
                        <option></option>
                        <option>Spectacle</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-right">
                    <button type="submit" class="btn btn-primary solid" style="margin-top: 10px;">Valider</button>
                </div>
            </div>
        </form>
    </div>
</div>

templates/video/_form_simple.html.twig
<div id="search">
    <form action="{{ path('app_video_search') }}" class="form-inline" style="float:right">
        <div class="form-group mb-6">
            <a class="btn btn-primary" data-toggle="collapse" href="#collapseVideoFilter" role="button" aria-expanded="false" aria-controls="collapseVideoFilter">
                <i class="fa fa-sliders"></i>&nbsp; &nbsp; FILTRER
            </a>
        </div>
        <div class="form-group mb-6">
            &nbsp;
            <input class="form-control form-control-lg" name="search" placeholder="search" type="search" value="{{ app.request.get('search') }}">
        </div>
     </form>
</div>

templates/video/_grid.html.twig
<div class="row">
    {% for video in videos %}
        <div class="col-sm-3 portfolio-static-item">
            <div class="grid">
                <a href="{{ path('app_video_show', {'id': video.id }) }}">
                    <figure class="m-0 effect-oscar">
                        <img src="https://img.youtube.com/vi/{{ video.youtubeId }}/0.jpg" alt="{{ video.name|e }}">
                    </figure>
                </a>
                <div class="portfolio-static-desc">
                    <h3><a href="{{ path('app_video_show', {'id': video.id }) }}">{{ video.name|e }}</a></h3>
                    <span><a href="#">{{ video.country|country }}</a></span>
                </div>
            </div>
            <!--/ grid end -->
        </div>
        <!--/ item 1 end -->
    {% endfor %}
</div>

templates/video/_listing.html.twig
{% for video in videos %}
    <div class="row">
        <div class="col-sm-3">
            <div class="grid">
                <a href="{{ path('app_video_show', {'id': video.id }) }}">
                    <figure class="m-0 effect-oscar">
                        <img src="https://img.youtube.com/vi/{{ video.youtubeId }}/0.jpg" alt="{{ video.name|e }}">
                    </figure>
                </a>
            </div>
            <!--/ grid end -->
        </div>
        <div class="col-sm-9">
            <div class="portfolio-static-desc">
                <h3 style="font-size: 24px"><a href="{{ path('app_video_show', {'id': video.id }) }}">{{ video.name|e }}</a></h3>
                <div class="video-meta meta-line1">
                    {% if video.event is not null %}
                        <span class="video-meta meta-event">
                            <i class="fa fa-calendar"></i> <a href="{{ path('app_video_search', { 'event': video.event.id }) }}">{{ video.event }}</a>
                            {% if video.event.date is not null %}
                                <span>•</span>
                                <span>{{ video.event.date|date('d/m/y') }}</span>
                            {% endif %}
                        </span>
                    {% endif %}
                </div>

                <div class="video-meta meta-line2">
                    {% if video.country is not null %}
                        <span class="video-meta meta-country">
                            <i class="fa fa-flag"></i> <a href="{{ path('app_video_search', { 'country': video.country }) }}">{{ video.country|country }}</a>
                        </span>                        &nbsp;
                    {% endif %}

                    {% if video.sections|length > 0 %}
                        <span class="video-meta meta-sections">
                            <i class="fa fa-users"></i>
                            {% for section in video.sections %}
                                <a href="{{ path('app_video_search', { 'sections': section.id }) }}">{{ section }}</a>
                                {% if not loop.last %},{% endif %}
                            {% endfor %}
                        </span>
                    {% endif %}
                </div>

                <div class="video-meta meta-line2">
                    {% if video.country is not null %}
                        <div class="video-meta meta-tags"><i class="fa fa-tags"></i> <a href="#">Spectacles</a></div>
                    {% endif %}
                </div>

                <div class="video-meta meta-desc">
                    {# <p>{{ video.description }}</p> #}
                </div>
            </div>
        </div>
    </div>
{% else %}
    <p>Aucune vidéo trouvé</p>
    <!--/ item 1 end -->
{% endfor %}

templates/video/index.html.twig
{% extends 'layout.html.twig' %}

{% block banner_title %}Videos{% endblock %}
{% block title %}Videos{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-3 heading">
            <span class="title-icon classic pull-left"><i class="fa fa-film"></i></span>
            <h2 class="title classic">Vidéos</h2>
        </div>
        <div class="col-md-9">
            {{ include('video/_form_simple.html.twig') }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            {{ include('video/_form_filter.html.twig') }}
        </div>
    </div>

    {% include 'video/_grid.html.twig' %}

{% endblock %}

templates/video/search.html.twig
{% extends 'layout.html.twig' %}

{% block banner_title %}Video{% endblock %}
{% block title %}Video{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-3 heading">
            <span class="title-icon classic pull-left"><i class="fa fa-film"></i></span>
            <h2 class="title classic">Vidéos</h2>
        </div>
        <div class="col-md-9">
            {{ include('video/_form_simple.html.twig') }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            {{ include('video/_form_filter.html.twig') }}
        </div>
    </div>

    {% include 'video/_listing.html.twig' %}

{% endblock %}

templates/video/show.html.twig
{% extends 'layout.html.twig' %}

{% block banner_title %}{{ video.name|e }}{% endblock %}
{% block title %}{{ video.name|e }}{% endblock %}

{% block main %}
    <div class="row">
        <!-- Portfolio item slider start -->
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ video.youtubeId }}?rel=0" allowfullscreen></iframe>
            </div>
        </div>
        <!-- Portfolio item slider end -->

        <!-- sidebar start -->
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="sidebar">
                <div class="portfolio-desc">
                    <h3 class="widget-title">Description</h3>
                    <p>{{ video.description|raw }}</p>

                    {% if video.country is not null %}
                        <h3 class="widget-title">Pays</h3>
                        <p><a href="{{ path('app_video_search', { 'country': video.country }) }}">{{ video.country|country }}</a></p>
                    {% endif %}

                    {% if video.event is not null %}
                        <h3 class="widget-title">Event</h3>
                        <p><a href="{{ path('app_video_search', { 'event': video.event.id }) }}">{{ video.event }}</a></p>
                    {% endif %}

                    {% if video.sections|length > 0 %}
                    <h3 class="widget-title">Section</h3>
                    <p>
                        {% for section in video.sections %}
                            <a href="{{ path('app_video_search', { 'sections': section.id }) }}">{{ section }}</a>
                            {% if not loop.last %},{% endif %}
                        {% endfor %}
                    </p>
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- sidebar end -->
    </div>

{% endblock %}